Add ability to check address ranges
chamini2/hapi-auth-ip-whitelist pull request #5
Opened 2019-01-05 23:37 UTC by drallgood

This adds the ability to use CIDR formatted address ranges like `10.0.1.1/24` (10.0.1.1-10.0.1.255) or `10.0.0.1/8` (10.0.0.1-10.255.255.255)

2019-01-22 16:43 UTC, chamini2 commented
When starting the example server, http://localhost:3000/authenticated throws a 500. Can you check that out?

2019-01-28 02:02 UTC, drallgood commented
@chamini2 Good catch! I think I messed up the file when cherry picking the changes from another file.
Should be fixed now.

2019-01-28 20:04 UTC, chamini2 requested changes

2019-01-28 20:04 UTC, chamini2 commented on lib/index.js
> +          return false
Suggestion:
```js
const regularIP = ipLib.isV4Format(ip) || ipLib.isV6Format(ip);
const cidrIP = ip.includes("/") && ipLib.cidrSubnet(ip).contains(remoteAddress);

return regularIP && ipLib.isEqual(ip, remoteAddress) || cidrIP;
```

2019-02-06 17:53 UTC, drallgood commented
@chamini2 I made the requested changes

2019-02-12 02:57 UTC, chamini2 approved these changes

2019-02-12 02:57 UTC, merged

2019-02-12 02:57 UTC, chamini2 commented
Thank you for your contribution!